name = "Creatorio"
author = "Fungame2270 & Masterttt123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea695135645827671226ef9661c2c8acac3ce96fc7481bb4e34e304b12d62668"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
